import type { ProductListing } from "@/lib/search";

// Curated on 2026-09-12 from SerpApi Google Shopping merchant offers.
// These are static demo listings with direct merchant links; prices and stock can change.
export const demoBrowseListings: ProductListing[] = [
  {
    "id": "preload-amazon-in-0-boat-airdopes-141",
    "title": "boAt Airdopes 141",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹999",
    "numericPrice": 999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQszYt5rNfdO66C8_0I3UEmEG6yMRatXFQKmLsf9KjSlc4W_EhpI_D6a2EYQSXWRTPXADwS-_HnmDp0ozaaF6OH9Kwi7C3ZdUF1DH7PV79unmuWxb3DM3vY",
    "link": "https://www.amazon.in/Airdopes-141-Playtime-Resistance-Bluetooth/dp/B09N3ZNHTY?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AJ6SIZC8YQDZX",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-1-boat-airdopes-141",
    "title": "boAt Airdopes 141",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹999",
    "numericPrice": 999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQszYt5rNfdO66C8_0I3UEmEG6yMRatXFQKmLsf9KjSlc4W_EhpI_D6a2EYQSXWRTPXADwS-_HnmDp0ozaaF6OH9Kwi7C3ZdUF1DH7PV79unmuWxb3DM3vY",
    "link": "https://www.zepto.com/pn/boat-airdopes-141-tws-earbuds-with-mic-low-latency-enx-tech-42hrs-battery-fast-charge-iwp-ipx4-v51-bluetooth-earbuds-bold-black/pvid/fb3d6000-093e-4b20-ba5a-9e88094aded2?srsltid=AfmBOoo_4lar1AKZtIvMMyoH3s-p6d1O3Hq0Ny5h3_cm0NSi9DNEsaiB40A",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-bigbasket-com-2-boat-airdopes-141",
    "title": "boAt Airdopes 141",
    "store": "bigbasket.com",
    "domain": "bigbasket.com",
    "price": "₹899",
    "numericPrice": 899,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQszYt5rNfdO66C8_0I3UEmEG6yMRatXFQKmLsf9KjSlc4W_EhpI_D6a2EYQSXWRTPXADwS-_HnmDp0ozaaF6OH9Kwi7C3ZdUF1DH7PV79unmuWxb3DM3vY",
    "link": "https://www.bigbasket.com/pd/40322252/boat-airdopes-141-tws-earphones-bold-black-1-pc/?z=Ga9BX3pQL&utm_source=google&utm_medium=cpc&utm_term=%7Bkeyword%7D&utm_campaign=Global-PLA/",
    "availability": "Current listing on bigbasket.com",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-oneplus-bullets-wireless-z2",
    "title": "OnePlus Bullets Wireless Z2",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹899",
    "numericPrice": 899,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSYYK9RLJBaG-EEAfKt1soxn1mKjKloUtgvNHijoGQg8yNF_b4ihdsB9ADwVoP4s1fRcC7f0NKEpCMUJr0YFc-6-E20YL6u-5O1EYQOOIeFWWQdX3WnjCAJe1c",
    "link": "https://www.amazon.in/Original-Earphone-Neckband-Bluetooth-Greenuction/dp/B0H9M48G9F?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1OBAEHGM9FXSC",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-oneplus-bullets-wireless-z2",
    "title": "OnePlus Bullets Wireless Z2",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹699",
    "numericPrice": 699,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSYYK9RLJBaG-EEAfKt1soxn1mKjKloUtgvNHijoGQg8yNF_b4ihdsB9ADwVoP4s1fRcC7f0NKEpCMUJr0YFc-6-E20YL6u-5O1EYQOOIeFWWQdX3WnjCAJe1c",
    "link": "https://www.flipkart.com/gripzo-one-plus-bullets-wireless-z2-09-anc-neckband-bluetooth-green-true-wireless-bluetooth-gaming/p/itm532dffe1d262e?pid=ACCHQWTGFNDQBZZ8&lid=LSTACCHQWTGFNDQBZZ8WZAJ8R&marketplace=FLIPKART&cmpid=content_headphone_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-2-oneplus-bullets-wireless-z2",
    "title": "OnePlus Bullets Wireless Z2",
    "store": "Myntra - MNow",
    "domain": "myntra.com",
    "price": "₹2,299",
    "numericPrice": 2299,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSYYK9RLJBaG-EEAfKt1soxn1mKjKloUtgvNHijoGQg8yNF_b4ihdsB9ADwVoP4s1fRcC7f0NKEpCMUJr0YFc-6-E20YL6u-5O1EYQOOIeFWWQdX3WnjCAJe1c",
    "link": "http://www.myntra.com/Headphones/OnePlus/OnePlus-Bullets-Wireless-Z2-with-45dB-Hybrid-ANC-and-28-Hours-Playback-Neckband-Earphones-/24085336/buy",
    "availability": "Current listing on Myntra - MNow",
    "sourceType": "text"
  },
  {
    "id": "preload-oneplus-in-3-oneplus-bullets-wireless-z2",
    "title": "OnePlus Bullets Wireless Z2",
    "store": "OnePlus Official Store",
    "domain": "oneplus.in",
    "price": "₹1,899",
    "numericPrice": 1899,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSYYK9RLJBaG-EEAfKt1soxn1mKjKloUtgvNHijoGQg8yNF_b4ihdsB9ADwVoP4s1fRcC7f0NKEpCMUJr0YFc-6-E20YL6u-5O1EYQOOIeFWWQdX3WnjCAJe1c",
    "link": "https://www.oneplus.in/product/oneplus-bullets-wireless-z2-anc?sku=5481144042",
    "availability": "Current listing on OnePlus Official Store",
    "sourceType": "text"
  },
  {
    "id": "preload-ajio-com-0-sony-wh-1000xm5-headphones",
    "title": "Sony WH-1000XM5 Headphones",
    "store": "AJIO.com",
    "domain": "ajio.com",
    "price": "₹24,374",
    "numericPrice": 24374,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEnFoPdTSQGFCd0tRr8jMrNvj2O31ViIEKn9pIYyGynr1TqKhTCi6QCql3UOgJQfeH5jVU8XXc0sOWHbafYggF4FL10jhCRxEL7nBGg6peIvsAB5SQXMxBLno",
    "link": "https://www.ajio.com/sony-sony-wh-1000xm5-wireless-industry-leading-active-noise-cancelling-headphones-with-mic-with-auto-noise-cancelling-optimizer-8-mics-for-crystal-clear-hands-free-calling-google-fast-pair-swift-pair-and-alexa-voice-control-black/p/4931792460_multi#gmf",
    "availability": "Current listing on AJIO.com",
    "sourceType": "text"
  },
  {
    "id": "preload-tatacliq-com-1-sony-wh-1000xm5-headphones",
    "title": "Sony WH-1000XM5 Headphones",
    "store": "Tata CLiQ - Fashion",
    "domain": "tatacliq.com",
    "price": "₹26,499",
    "numericPrice": 26499,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEnFoPdTSQGFCd0tRr8jMrNvj2O31ViIEKn9pIYyGynr1TqKhTCi6QCql3UOgJQfeH5jVU8XXc0sOWHbafYggF4FL10jhCRxEL7nBGg6peIvsAB5SQXMxBLno",
    "link": "https://www.tatacliq.com/sony-wh-1000xm5-wireless-industry-leading-active-noise-cancelling-headphones-black/p-mp000000016239770",
    "availability": "Current listing on Tata CLiQ - Fashion",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-2-sony-wh-1000xm5-headphones",
    "title": "Sony WH-1000XM5 Headphones",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹27,989",
    "numericPrice": 27989,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEnFoPdTSQGFCd0tRr8jMrNvj2O31ViIEKn9pIYyGynr1TqKhTCi6QCql3UOgJQfeH5jVU8XXc0sOWHbafYggF4FL10jhCRxEL7nBGg6peIvsAB5SQXMxBLno",
    "link": "https://www.amazon.in/Sony-WH-1000XM5-Wireless-Cancelling-Headphones/dp/B09XS7JWHH?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AJ6SIZC8YQDZX",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-3-sony-wh-1000xm5-headphones",
    "title": "Sony WH-1000XM5 Headphones",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹27,990",
    "numericPrice": 27990,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTEnFoPdTSQGFCd0tRr8jMrNvj2O31ViIEKn9pIYyGynr1TqKhTCi6QCql3UOgJQfeH5jVU8XXc0sOWHbafYggF4FL10jhCRxEL7nBGg6peIvsAB5SQXMxBLno",
    "link": "https://www.flipkart.com/sony-wh-1000xm5-designed-adaptive-anc-30-hours-battery-life-bluetooth-wired/p/itm9ee097bc0ae76?pid=ACCHGBCB34ATPVM7&lid=LSTACCHGBCB34ATPVM72YDN3G&marketplace=FLIPKART&cmpid=content_headphone_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-jbl-tune-770nc-headphones",
    "title": "JBL Tune 770NC Headphones",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹5,999",
    "numericPrice": 5999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQo1GLslerkH2w5Fv7LH6c7BD3iSsPkHNx7Pcos3gBmzyK2TFoLM9oByHcQ1i5ZO0HE59wx2sJxNchLBGEOezAXkMMEGLp0sA813D6YXmiCwKxT28WFwr0EggU",
    "link": "https://www.amazon.in/JBL-Wireless-Headphones-Speedcharge-Customize/dp/B09CYX92NB?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AJ6SIZC8YQDZX",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-jbl-tune-770nc-headphones",
    "title": "JBL Tune 770NC Headphones",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹5,999",
    "numericPrice": 5999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQo1GLslerkH2w5Fv7LH6c7BD3iSsPkHNx7Pcos3gBmzyK2TFoLM9oByHcQ1i5ZO0HE59wx2sJxNchLBGEOezAXkMMEGLp0sA813D6YXmiCwKxT28WFwr0EggU",
    "link": "https://www.flipkart.com/jbl-tune-770nc-active-noise-cancelling-70hr-playtime-fast-pair-multi-connect-bluetooth-gaming/p/itmdf5c83684df50?pid=ACCGQZVZWZFFPGYE&lid=LSTACCGQZVZWZFFPGYEMQH3AK&marketplace=FLIPKART&cmpid=content_headphone_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-in-jbl-com-2-jbl-tune-770nc-headphones",
    "title": "JBL Tune 770NC Headphones",
    "store": "JBL India",
    "domain": "in.jbl.com",
    "price": "₹5,999",
    "numericPrice": 5999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQo1GLslerkH2w5Fv7LH6c7BD3iSsPkHNx7Pcos3gBmzyK2TFoLM9oByHcQ1i5ZO0HE59wx2sJxNchLBGEOezAXkMMEGLp0sA813D6YXmiCwKxT28WFwr0EggU",
    "link": "https://in.jbl.com/JBLT770NCBLK.html",
    "availability": "Current listing on JBL India",
    "sourceType": "text"
  },
  {
    "id": "preload-luxury-tatacliq-com-3-jbl-tune-770nc-headphones",
    "title": "JBL Tune 770NC Headphones",
    "store": "TATA CLiQ LUXURY",
    "domain": "luxury.tatacliq.com",
    "price": "₹5,999",
    "numericPrice": 5999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQo1GLslerkH2w5Fv7LH6c7BD3iSsPkHNx7Pcos3gBmzyK2TFoLM9oByHcQ1i5ZO0HE59wx2sJxNchLBGEOezAXkMMEGLp0sA813D6YXmiCwKxT28WFwr0EggU",
    "link": "https://luxury.tatacliq.com/jbl-tune-770nc-over-ear-wireless-bluetooth-headphones-with-anc-upto-70-hrs-playtime-black/p-mp000000022898685?srsltid=AfmBOorvSWTx4MMQxnQhEUsEyWUW2Sr03Z1rkyI9S9fkpMpKktuU49bwD0E",
    "availability": "Current listing on TATA CLiQ LUXURY",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-0-apple-airpods-pro-2nd-generation",
    "title": "Apple AirPods Pro 2nd Generation",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹482",
    "numericPrice": 482,
    "image": "https://rukminim2.flixcart.com/image/1500/1500/xif0q/headphone/o/u/i/airpods-pro-2-2nd-generation-wireless-headphone-with-anc-original-imahg5fygfp7gdbq.jpeg",
    "link": "https://www.flipkart.com/bmjncj-airpods-pro-2-2nd-generation-wireless-headphone-anc-bluetooth/p/itm60e83954ddcd9",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-gulfmarket-in-1-apple-airpods-pro-2nd-generation",
    "title": "Apple AirPods Pro 2nd Generation",
    "store": "Gulfmarket.in",
    "domain": "gulfmarket.in",
    "price": "₹529",
    "numericPrice": 529,
    "image": "https://rukminim2.flixcart.com/image/1500/1500/xif0q/headphone/o/u/i/airpods-pro-2-2nd-generation-wireless-headphone-with-anc-original-imahg5fygfp7gdbq.jpeg",
    "link": "https://gulfmarket.in/product.php?productid=2088&srsltid=AfmBOooAmlvfR3k5kh1c67ubrif2hE9Nr_fiYT-U7sbWao5Yr4bMBEy3LZU",
    "availability": "Current listing on Gulfmarket.in",
    "sourceType": "text"
  },
  {
    "id": "preload-tradeindia-com-2-apple-airpods-pro-2nd-generation",
    "title": "Apple AirPods Pro 2nd Generation",
    "store": "Tradeindia.com",
    "domain": "tradeindia.com",
    "price": "₹445",
    "numericPrice": 445,
    "image": "https://rukminim2.flixcart.com/image/1500/1500/xif0q/headphone/o/u/i/airpods-pro-2-2nd-generation-wireless-headphone-with-anc-original-imahg5fygfp7gdbq.jpeg",
    "link": "https://www.tradeindia.com/products/airpod-pro-2-a10-type-c-c11490052.html",
    "availability": "Current listing on Tradeindia.com",
    "sourceType": "text"
  },
  {
    "id": "preload-banjaraelectronics-com-0-samsung-galaxy-buds2-pro",
    "title": "Samsung Galaxy Buds2 Pro",
    "store": "Banjara Electronics",
    "domain": "banjaraelectronics.com",
    "price": "₹4,990",
    "numericPrice": 4990,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSc-OqIRG0dPmaUK92cBy9E8VYE66lBu8nS0uPOtql-voqBebOQwoa0MT8Q1vgTc35fvBi7I7nY2JMZzyp7PzrmhqOBe59XWgfI0lMUZTV1nUtzI67YNsWPxQ",
    "link": "https://banjaraelectronics.com/products/samsung-galaxy-buds2-pro-with-innovative-ai-features-bluetooth-truly-wireless-in-ear-earbuds-with-no?sku_id=58319961&srsltid=AfmBOoovlxPijZeTvj-s2lpwIr_P23fncIXiNrx3FuNdauvhr0eaMXlhbCs",
    "availability": "Current listing on Banjara Electronics",
    "sourceType": "text"
  },
  {
    "id": "preload-vlebazaar-in-1-samsung-galaxy-buds2-pro",
    "title": "Samsung Galaxy Buds2 Pro",
    "store": "vlebazaar.in",
    "domain": "vlebazaar.in",
    "price": "₹10,999",
    "numericPrice": 10999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSc-OqIRG0dPmaUK92cBy9E8VYE66lBu8nS0uPOtql-voqBebOQwoa0MT8Q1vgTc35fvBi7I7nY2JMZzyp7PzrmhqOBe59XWgfI0lMUZTV1nUtzI67YNsWPxQ",
    "link": "https://vlebazaar.in/samsung-galaxy-buds2-pro-bluetooth?srsltid=AfmBOop_QMOwHamQE2rjHAWK6yxQha5C5qvL3DX5fvhmT4PN5AkNth8hZ3g",
    "availability": "Current listing on vlebazaar.in",
    "sourceType": "text"
  },
  {
    "id": "preload-ubuy-co-in-2-samsung-galaxy-buds2-pro",
    "title": "Samsung Galaxy Buds2 Pro",
    "store": "ubuy.co.in",
    "domain": "ubuy.co.in",
    "price": "₹14,161",
    "numericPrice": 14161,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSc-OqIRG0dPmaUK92cBy9E8VYE66lBu8nS0uPOtql-voqBebOQwoa0MT8Q1vgTc35fvBi7I7nY2JMZzyp7PzrmhqOBe59XWgfI0lMUZTV1nUtzI67YNsWPxQ",
    "link": "https://www.ubuy.co.in/product/TYIUJ9W9K-samsung-galaxy-buds2-pro-graphite?srsltid=AfmBOorEz_DuXAAs70EESXRSerNkrp9YS1EmXUVn84ArQRZzQLXn9ICIqHU",
    "availability": "Current listing on ubuy.co.in",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-nothing-ear-a-earbuds",
    "title": "Nothing Ear a Earbuds",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹7,588",
    "numericPrice": 7588,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTGSmtXbNIU91CAoF1exKdzpyCIKgVbQBp6gCB0i5h9Q8w95uJbbdDYKLQ65_Fd0hzxzE7K-LKpCC2Y1xDf90wJO8aVODV_O380jGSC4Nclzp8HFKMkRVNW",
    "link": "https://www.amazon.in/Nothing-Ear-Bluetooth-Headset-Wireless/dp/B0D2MW6L54?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A2FC3PE9RGC9HU",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-1-nothing-ear-a-earbuds",
    "title": "Nothing Ear a Earbuds",
    "store": "Myntra - MNow",
    "domain": "myntra.com",
    "price": "₹7,999",
    "numericPrice": 7999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTGSmtXbNIU91CAoF1exKdzpyCIKgVbQBp6gCB0i5h9Q8w95uJbbdDYKLQ65_Fd0hzxzE7K-LKpCC2Y1xDf90wJO8aVODV_O380jGSC4Nclzp8HFKMkRVNW",
    "link": "http://www.myntra.com/Headphones/Nothing/Nothing-Ear-a-Chat-GPT-Compatible-Hi-Res-audio-LDAC-Bluetooth/28638650/buy",
    "availability": "Current listing on Myntra - MNow",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-nothing-ear-a-earbuds",
    "title": "Nothing Ear a Earbuds",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹7,999",
    "numericPrice": 7999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTGSmtXbNIU91CAoF1exKdzpyCIKgVbQBp6gCB0i5h9Q8w95uJbbdDYKLQ65_Fd0hzxzE7K-LKpCC2Y1xDf90wJO8aVODV_O380jGSC4Nclzp8HFKMkRVNW",
    "link": "https://www.flipkart.com/nothing-ear-a-2024-chatgpt-compatible-hi-res-audio-ldac-bluetooth/p/itm8da590d5343d2?pid=ACCGZ6Q3X3W3TZWX&lid=LSTACCGZ6Q3X3W3TZWXTHSA9B&marketplace=FLIPKART&cmpid=content_headphone_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-mi-com-0-redmi-buds-5",
    "title": "Redmi Buds 5",
    "store": "Mi.com",
    "domain": "mi.com",
    "price": "₹2,999",
    "numericPrice": 2999,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ-2_s03ORjL3-v7D-la8dd4Wt3-ioeUe_jxqWXdB6lq9zbh945_djuB6lg8Qs_lTYgMWn2ZUjwQVXX8vItzk7VgTF9Q_TJzQ",
    "link": "https://www.mi.com/in/product/redmi-buds-5?srsltid=AfmBOoqn1TyVXIVwG8zhnFuh8ZMGxSn-IuTTz5moy6hxCekAr3WF5IE3XUY",
    "availability": "Current listing on Mi.com",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-redmi-buds-5",
    "title": "Redmi Buds 5",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹1,699",
    "numericPrice": 1699,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ-2_s03ORjL3-v7D-la8dd4Wt3-ioeUe_jxqWXdB6lq9zbh945_djuB6lg8Qs_lTYgMWn2ZUjwQVXX8vItzk7VgTF9Q_TJzQ",
    "link": "https://www.flipkart.com/redmi-buds-5-46db-hybrid-anc-earbuds-quad-mic-ai-enc-dual-device-connection-bluetooth/p/itme460d723f761c?pid=ACCGXMYDASUYSJBR&lid=LSTACCGXMYDASUYSJBR2EXLVT&marketplace=FLIPKART&cmpid=content_headphone_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-2-redmi-buds-5",
    "title": "Redmi Buds 5",
    "store": "Myntra - MNow",
    "domain": "myntra.com",
    "price": "₹2,999",
    "numericPrice": 2999,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ-2_s03ORjL3-v7D-la8dd4Wt3-ioeUe_jxqWXdB6lq9zbh945_djuB6lg8Qs_lTYgMWn2ZUjwQVXX8vItzk7VgTF9Q_TJzQ",
    "link": "http://www.myntra.com/Headphones/Redmi/Redmi-buds-5-Truly-Wireless-Bluetooth-Ear-Buds/31029945/buy",
    "availability": "Current listing on Myntra - MNow",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-0-apple-watch-se",
    "title": "Apple Watch SE",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹24,999",
    "numericPrice": 24999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSzFD6rq_BqNMxK8oQbEwDpU_HR9fmW1gNwtUMgIPmR4Bi9_zMwJkA3GH5dtvdRMQgushFLY-e3Wr8gcLMe_7O2O6Jn7Ft_",
    "link": "http://www.flipkart.com/apple-watch-se-2-gps-44mm-2nd-gen-midnight-aluminium-sport-band/p/itmb7bf8510e794d?pid=SMWH4JBWBYQ6QBGK&lid=LSTSMWH4JBWBYQ6QBGKWWJZ5K&marketplace=HYPERLOCAL&cmpid=content_smartwatch_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-snapmint-com-1-apple-watch-se",
    "title": "Apple Watch SE",
    "store": "EMI Snapmint",
    "domain": "snapmint.com",
    "price": "₹23,999",
    "numericPrice": 23999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSzFD6rq_BqNMxK8oQbEwDpU_HR9fmW1gNwtUMgIPmR4Bi9_zMwJkA3GH5dtvdRMQgushFLY-e3Wr8gcLMe_7O2O6Jn7Ft_",
    "link": "https://snapmint.com/p/apple-watch-se-2nd-gen-gps-44mm-smartwatch-with-midnight-aluminum-case-with-midnight-sport-band-smart-watches-on-emi?srsltid=AfmBOopAnHydboDdfLVkrx9OfMmFQra2Xs1IWDhGjIA3u0kfURHlJp7h5Mw",
    "availability": "Current listing on EMI Snapmint",
    "sourceType": "text"
  },
  {
    "id": "preload-fonezone-com-2-apple-watch-se",
    "title": "Apple Watch SE",
    "store": "FoneZone.com",
    "domain": "fonezone.com",
    "price": "₹16,440.37",
    "numericPrice": 16440.37,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSzFD6rq_BqNMxK8oQbEwDpU_HR9fmW1gNwtUMgIPmR4Bi9_zMwJkA3GH5dtvdRMQgushFLY-e3Wr8gcLMe_7O2O6Jn7Ft_",
    "link": "https://fonezone.com/products/apple-watch-se-2nd-gen-gps-aluminum-44mm?currency=INR&country=IN&variant=46087684751404&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=076b83324738&srsltid=AfmBOor6b8WVOOveUADmemA_8yXxKoDVwg1LxOkuV7YkisiIUe1NU3HkIKA",
    "availability": "Current listing on FoneZone.com",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-titan-karishma-analog-watch",
    "title": "Titan Karishma Analog Watch",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹1,935",
    "numericPrice": 1935,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTIh8KekvGlxlBIT546JPs38DI8l83Gaz812lBRh5vLUbw6gYx7eCirnzNpV9_Ju5yZhVt_iuohctoetdIl6oLJhr3mGx1jg0krXcT_oFyoA2QWZl3uzIDjZw",
    "link": "https://www.amazon.in/Titan-Multi-Colour-Stainless-Watch-NL1639SM01-NN1639SM01/dp/B00ISNVM0S?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1JFLV2BUSJ5AK",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-tatacliq-com-1-titan-karishma-analog-watch",
    "title": "Titan Karishma Analog Watch",
    "store": "Tata CLiQ Fashion",
    "domain": "tatacliq.com",
    "price": "₹1,995",
    "numericPrice": 1995,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTIh8KekvGlxlBIT546JPs38DI8l83Gaz812lBRh5vLUbw6gYx7eCirnzNpV9_Ju5yZhVt_iuohctoetdIl6oLJhr3mGx1jg0krXcT_oFyoA2QWZl3uzIDjZw",
    "link": "https://www.tatacliq.com/titan-nn1639sm01-karishma-analog-watch-for-men/p-mp000000009418919",
    "availability": "Current listing on Tata CLiQ Fashion",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-titan-karishma-analog-watch",
    "title": "Titan Karishma Analog Watch",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹1,995",
    "numericPrice": 1995,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTIh8KekvGlxlBIT546JPs38DI8l83Gaz812lBRh5vLUbw6gYx7eCirnzNpV9_Ju5yZhVt_iuohctoetdIl6oLJhr3mGx1jg0krXcT_oFyoA2QWZl3uzIDjZw",
    "link": "https://www.flipkart.com/titan-karishma-silver-dial-stainless-steel-strap-analog-watch-men/p/itm4f9a928739cd6?pid=WATDTWVVBG2XFYJU&lid=LSTWATDTWVVBG2XFYJUPHYATT&marketplace=FLIPKART&cmpid=content_watch_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-casio-vintage-a168wa-watch",
    "title": "Casio Vintage A168WA Watch",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹2,694",
    "numericPrice": 2694,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQhm4_3OqB2TxgX5qJ6QojQ0pX7KZBuZEcM39skxra5pYWnPXEYv0kION4O_ZFekm9dQ0hJvrsD2i4wQ82YF2sOD8tenGEKAdw7qSUJrZaSH9GtcJNuzR_wMg",
    "link": "https://www.amazon.in/Casio-Vintage-Digital-Multi-Colour-Watch-A168WA-1WDF/dp/B00JAK1PMI?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1JFLV2BUSJ5AK",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-1-casio-vintage-a168wa-watch",
    "title": "Casio Vintage A168WA Watch",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹2,695",
    "numericPrice": 2695,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQhm4_3OqB2TxgX5qJ6QojQ0pX7KZBuZEcM39skxra5pYWnPXEYv0kION4O_ZFekm9dQ0hJvrsD2i4wQ82YF2sOD8tenGEKAdw7qSUJrZaSH9GtcJNuzR_wMg",
    "link": "http://www.myntra.com/Watches/CASIO/CASIO-Vintage-A168WA-1WDF-Black-Digital-Dial-Silver-Stainless-Steel-Band-D131/7370454/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-swisstimehouse-com-2-casio-vintage-a168wa-watch",
    "title": "Casio Vintage A168WA Watch",
    "store": "Swiss Time House",
    "domain": "swisstimehouse.com",
    "price": "₹2,695",
    "numericPrice": 2695,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQhm4_3OqB2TxgX5qJ6QojQ0pX7KZBuZEcM39skxra5pYWnPXEYv0kION4O_ZFekm9dQ0hJvrsD2i4wQ82YF2sOD8tenGEKAdw7qSUJrZaSH9GtcJNuzR_wMg",
    "link": "https://www.swisstimehouse.com/casio-d131-a168wa-1wdf-vintage-unisex-watch?srsltid=AfmBOooeG-xuVMORKaVAkNLlNdFQ9oE3uv0B8KvL0CFv6_-NH4oOkamPxB4",
    "availability": "Current listing on Swiss Time House",
    "sourceType": "text"
  },
  {
    "id": "preload-ajio-com-0-fastrack-reflex-vox-smartwatch",
    "title": "Fastrack Reflex Vox Smartwatch",
    "store": "AJIO.com",
    "domain": "ajio.com",
    "price": "₹2,691",
    "numericPrice": 2691,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTtgYgOT4HUFHucN81vMQFJ3Nognz1GyPyOYS0JEztHhoy_qKjLB95oYjIxHV0Yxa6oMfQ-fnz7YmkapPbmtBYkiCFtXmtZmuqS92WuRVwyPkNSnCgZGPOiyQE",
    "link": "https://www.ajio.com/fastrack-women-water-resistant-analogue-watch-nt6292wm01/p/4934144400_multi#gmf",
    "availability": "Current listing on AJIO.com",
    "sourceType": "text"
  },
  {
    "id": "preload-titan-co-in-1-fastrack-reflex-vox-smartwatch",
    "title": "Fastrack Reflex Vox Smartwatch",
    "store": "Titan.co.in",
    "domain": "titan.co.in",
    "price": "₹2,715",
    "numericPrice": 2715,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTtgYgOT4HUFHucN81vMQFJ3Nognz1GyPyOYS0JEztHhoy_qKjLB95oYjIxHV0Yxa6oMfQ-fnz7YmkapPbmtBYkiCFtXmtZmuqS92WuRVwyPkNSnCgZGPOiyQE",
    "link": "https://www.titan.co.in/product/fastrack-crush-quartz-analog-watch-for-girls-with-blue-dial-stainless-steel-strap-6292qm02.html?lang=en_IN&nsbp=true&srsltid=AfmBOor9AxHDnxNJ0IGf2lxmfqQzF3CZyZ5BZw1aUbfee57q8cqUjdeXznM",
    "availability": "Current listing on Titan.co.in",
    "sourceType": "text"
  },
  {
    "id": "preload-fastrack-in-2-fastrack-reflex-vox-smartwatch",
    "title": "Fastrack Reflex Vox Smartwatch",
    "store": "Fastrack.in",
    "domain": "fastrack.in",
    "price": "₹2,715",
    "numericPrice": 2715,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTtgYgOT4HUFHucN81vMQFJ3Nognz1GyPyOYS0JEztHhoy_qKjLB95oYjIxHV0Yxa6oMfQ-fnz7YmkapPbmtBYkiCFtXmtZmuqS92WuRVwyPkNSnCgZGPOiyQE",
    "link": "https://www.fastrack.in/product/fastrack-crush-quartz-analog-watch-for-girls-with-blue-dial-stainless-steel-strap-6292qm02.html?lang=en_IN&nsbp=true",
    "availability": "Current listing on Fastrack.in",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-0-noise-colorfit-pro-5",
    "title": "Noise ColorFit Pro 5",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹2,999",
    "numericPrice": 2999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS7PoA3CVcGsm9OHP_bfS1LVLYDto-bHet0sg3bcXtf-gawawWXFyxG8pVtkY-1CsiUZYl9e5MehLREObFqV-eoGdtImHuoEQ7nPcZ29trACZQi8EpXl52Efw",
    "link": "https://www.zepto.com/pn/noise-colorfit-pro-5-44mm-smartwatch-midnight-black/pvid/dfff8c81-a7b4-4b39-adbf-254187f1e5e6?srsltid=AfmBOoqIIZ0OJvlqM9bYzTqinczyhAalQd81FihmkiIT-l5bNX4VK99Wygc",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-noise-colorfit-pro-5",
    "title": "Noise ColorFit Pro 5",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹2,999",
    "numericPrice": 2999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS7PoA3CVcGsm9OHP_bfS1LVLYDto-bHet0sg3bcXtf-gawawWXFyxG8pVtkY-1CsiUZYl9e5MehLREObFqV-eoGdtImHuoEQ7nPcZ29trACZQi8EpXl52Efw",
    "link": "https://www.flipkart.com/noise-pro-5-1-85-amoled-always-on-display-diy-watch-face-sos-technology-bt-calling-smartwatch/p/itmf3996f6037087?pid=SMWGSGT48J5TMHYN&lid=LSTSMWGSGT48J5TMHYNFQF92J&marketplace=FLIPKART&cmpid=content_smartwatch_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-croma-com-2-noise-colorfit-pro-5",
    "title": "Noise ColorFit Pro 5",
    "store": "Croma",
    "domain": "croma.com",
    "price": "₹3,999",
    "numericPrice": 3999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS7PoA3CVcGsm9OHP_bfS1LVLYDto-bHet0sg3bcXtf-gawawWXFyxG8pVtkY-1CsiUZYl9e5MehLREObFqV-eoGdtImHuoEQ7nPcZ29trACZQi8EpXl52Efw",
    "link": "https://www.croma.com/noise-colorfit-pro-5-smartwatch-with-bluetooth-calling-46-99mm-amoled-display-ip68-water-resistant-midnight-black-strap-/p/302645?srsltid=AfmBOoq_baUC3OLVtXnrKeLZM-sO7feiOxBkMxQfNtd3Uq417i_Fg_wfR1U",
    "availability": "Current listing on Croma",
    "sourceType": "text"
  },
  {
    "id": "preload-nykaa-com-0-maybelline-superstay-matte-ink",
    "title": "Maybelline SuperStay Matte Ink",
    "store": "Nykaa Now",
    "domain": "nykaa.com",
    "price": "₹412",
    "numericPrice": 412,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSC2BzsyzoQpDBE1DUkxBpFxU2Xu5IF7_rLddc9Rb_3iB-cCnJsJP3xXcmS0cM-WEnVXJyPr6CuKEK281ImUtVVAZWAQMU8rpFE7w2AT0NCp4vZd1htD6XQHho",
    "link": "https://www.nykaa.com/maybelline-new-york-superstay-matte-ink-liquid-lipstick/p/229917?ptype=product&skuId=21884049",
    "availability": "Current listing on Nykaa Now",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-1-maybelline-superstay-matte-ink",
    "title": "Maybelline SuperStay Matte Ink",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹374",
    "numericPrice": 374,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSC2BzsyzoQpDBE1DUkxBpFxU2Xu5IF7_rLddc9Rb_3iB-cCnJsJP3xXcmS0cM-WEnVXJyPr6CuKEK281ImUtVVAZWAQMU8rpFE7w2AT0NCp4vZd1htD6XQHho",
    "link": "http://www.myntra.com/Lipstick/Maybelline/Maybelline-New-York-Superstay-Matte-Ink-Matte-Liquid-Lipstick-5ml---Validator/36086461/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-ajio-com-2-maybelline-superstay-matte-ink",
    "title": "Maybelline SuperStay Matte Ink",
    "store": "AJIO.com",
    "domain": "ajio.com",
    "price": "₹637",
    "numericPrice": 637,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSC2BzsyzoQpDBE1DUkxBpFxU2Xu5IF7_rLddc9Rb_3iB-cCnJsJP3xXcmS0cM-WEnVXJyPr6CuKEK281ImUtVVAZWAQMU8rpFE7w2AT0NCp4vZd1htD6XQHho",
    "link": "https://www.ajio.com/maybelline-new-york-superstay-matte-ink-liquid-lipstick--validator/p/4946250620_validator#gmf",
    "availability": "Current listing on AJIO.com",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-3-maybelline-superstay-matte-ink",
    "title": "Maybelline SuperStay Matte Ink",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹749",
    "numericPrice": 749,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSC2BzsyzoQpDBE1DUkxBpFxU2Xu5IF7_rLddc9Rb_3iB-cCnJsJP3xXcmS0cM-WEnVXJyPr6CuKEK281ImUtVVAZWAQMU8rpFE7w2AT0NCp4vZd1htD6XQHho",
    "link": "https://www.amazon.in/Maybelline-Superstay-Matte-Liquid-Lipstick/dp/B09FXWF9B7?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1LZ7G0KNVECJS",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-lakme-eyeconic-kajal",
    "title": "Lakme Eyeconic Kajal",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹131",
    "numericPrice": 131,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx9nZACZLzcsCazYzJMZ3evSKcYFr3HEe3bpBE673heGqZo-VWn_Ebnv8B7Iwat6ZMJiWsbDmKV1gxzYe83CjNrQGrJTSqTCpIbFPu8gFAKhRYZdgjLkejmHU",
    "link": "https://www.amazon.in/LAKM%C3%89-Eyeconic-Midnight-Blue-0-35g/dp/B0C3VF7HRT?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A15APWRK6P7LBV",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-ajio-com-1-lakme-eyeconic-kajal",
    "title": "Lakme Eyeconic Kajal",
    "store": "AJIO.com",
    "domain": "ajio.com",
    "price": "₹296",
    "numericPrice": 296,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx9nZACZLzcsCazYzJMZ3evSKcYFr3HEe3bpBE673heGqZo-VWn_Ebnv8B7Iwat6ZMJiWsbDmKV1gxzYe83CjNrQGrJTSqTCpIbFPu8gFAKhRYZdgjLkejmHU",
    "link": "https://www.ajio.com/lakme-eyeconic-kajal-matte-waterproof-smudgeproof-kajal-that-lasts-24-hrs--midnight-blue-0-35-g-/p/4938573300_midnightblue#gmf",
    "availability": "Current listing on AJIO.com",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-2-lakme-eyeconic-kajal",
    "title": "Lakme Eyeconic Kajal",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹220",
    "numericPrice": 220,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx9nZACZLzcsCazYzJMZ3evSKcYFr3HEe3bpBE673heGqZo-VWn_Ebnv8B7Iwat6ZMJiWsbDmKV1gxzYe83CjNrQGrJTSqTCpIbFPu8gFAKhRYZdgjLkejmHU",
    "link": "http://www.myntra.com/Kajal/Lakme/Lakme-9to5-Eyeconic-Smudgeproof--Waterproof-Kajal-Lasts-Upto-24Hr-035g---Midnight-Blue-/23299530/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-tirabeauty-com-3-lakme-eyeconic-kajal",
    "title": "Lakme Eyeconic Kajal",
    "store": "Tira",
    "domain": "tirabeauty.com",
    "price": "₹131",
    "numericPrice": 131,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx9nZACZLzcsCazYzJMZ3evSKcYFr3HEe3bpBE673heGqZo-VWn_Ebnv8B7Iwat6ZMJiWsbDmKV1gxzYe83CjNrQGrJTSqTCpIbFPu8gFAKhRYZdgjLkejmHU",
    "link": "https://www.tirabeauty.com/product/lakme-eyeconic-kajal-midnight-blue-0-35g-7567544?srsltid=AfmBOoofi73wK9bEy27zkjSX9CTn4Wu9vncUv-j-kzL6V6JJpHjQk4H0j_o",
    "availability": "Current listing on Tira",
    "sourceType": "text"
  },
  {
    "id": "preload-beminimalist-co-0-minimalist-10-niacinamide-serum",
    "title": "Minimalist 10% Niacinamide Serum",
    "store": "Minimalist",
    "domain": "beminimalist.co",
    "price": "₹899",
    "numericPrice": 899,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-jCeyf4pxx643Hp8LfRAgQ02sgFPb2fMwVEMQAzZwvyCnWDJfH--unowWPcqOoyURKZOdenQR2F5V1T_MT4ILaowFM9jbyCSTNdaBVzX-ra2yvKBIagNMtA",
    "link": "https://beminimalist.co/products/niacinamide-10-with-matmarine?currency=INR&country=IN&variant=44802331181217&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=f4faea6d89b6&srsltid=AfmBOopFn7cXF1mxDr_mc4JJRoqLUxkzOwD2OA2yGnZaKKwEfR0X0Msgk58",
    "availability": "Current listing on Minimalist",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-minimalist-10-niacinamide-serum",
    "title": "Minimalist 10% Niacinamide Serum",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹427",
    "numericPrice": 427,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-jCeyf4pxx643Hp8LfRAgQ02sgFPb2fMwVEMQAzZwvyCnWDJfH--unowWPcqOoyURKZOdenQR2F5V1T_MT4ILaowFM9jbyCSTNdaBVzX-ra2yvKBIagNMtA",
    "link": "https://www.amazon.in/Minimalist-10-Niacinamide-Serum-Zinc/dp/B0HBBBKSBH?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A3OQ22QWZ4ZJKQ",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-minimalist-10-niacinamide-serum",
    "title": "Minimalist 10% Niacinamide Serum",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹949",
    "numericPrice": 949,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-jCeyf4pxx643Hp8LfRAgQ02sgFPb2fMwVEMQAzZwvyCnWDJfH--unowWPcqOoyURKZOdenQR2F5V1T_MT4ILaowFM9jbyCSTNdaBVzX-ra2yvKBIagNMtA",
    "link": "https://www.flipkart.com/minimalist-10-niacinamide-face-serum-acne-marks-blemishes-oil-balancing-zinc-skin-clarifying-anti-oily-prone/p/itm66463d4ac2142?pid=KMTH5Q48GZTPKP2E&lid=LSTKMTH5Q48GZTPKP2ECNU5EK&marketplace=FLIPKART&cmpid=content_skin-treatment_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-tirabeauty-com-3-minimalist-10-niacinamide-serum",
    "title": "Minimalist 10% Niacinamide Serum",
    "store": "Tira",
    "domain": "tirabeauty.com",
    "price": "₹949",
    "numericPrice": 949,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ-jCeyf4pxx643Hp8LfRAgQ02sgFPb2fMwVEMQAzZwvyCnWDJfH--unowWPcqOoyURKZOdenQR2F5V1T_MT4ILaowFM9jbyCSTNdaBVzX-ra2yvKBIagNMtA",
    "link": "https://www.tirabeauty.com/product/minimalist-niacinamide-10-face-serum-60-ml-7618796?srsltid=AfmBOopa6euMOCdvD594_XwBsZvAZ_UgM4do-_yz3Yz2ubJzHDou2zzHhHI",
    "availability": "Current listing on Tira",
    "sourceType": "text"
  },
  {
    "id": "preload-nykaa-com-0-the-ordinary-glycolic-acid-7-toning-solution",
    "title": "The Ordinary Glycolic Acid 7% Toning Solution",
    "store": "Nykaa Now",
    "domain": "nykaa.com",
    "price": "₹900",
    "numericPrice": 900,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYHrNPhlRDuhMx0UlYi1IWGwPSYw8b1ZAKxvrCnj6JJWwivikSyacBYlTfrqCa2i9JRIDMZSTPra1LQrptWhQKoNGjhhkWfIgWocLu8_APJul3cDS9gvykuQ",
    "link": "https://www.nykaa.com/the-ordinary-glycolic-acid-7percent-exfoliating-solution/p/13025179?ptype=product&skuId=18116044",
    "availability": "Current listing on Nykaa Now",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-the-ordinary-glycolic-acid-7-toning-solution",
    "title": "The Ordinary Glycolic Acid 7% Toning Solution",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹900",
    "numericPrice": 900,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYHrNPhlRDuhMx0UlYi1IWGwPSYw8b1ZAKxvrCnj6JJWwivikSyacBYlTfrqCa2i9JRIDMZSTPra1LQrptWhQKoNGjhhkWfIgWocLu8_APJul3cDS9gvykuQ",
    "link": "https://www.amazon.in/Ordinary-Exfoliating-Brightening-Smoothing-Even-Looking/dp/B0DMTDN158?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A15APWRK6P7LBV",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-2-the-ordinary-glycolic-acid-7-toning-solution",
    "title": "The Ordinary Glycolic Acid 7% Toning Solution",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹900",
    "numericPrice": 900,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYHrNPhlRDuhMx0UlYi1IWGwPSYw8b1ZAKxvrCnj6JJWwivikSyacBYlTfrqCa2i9JRIDMZSTPra1LQrptWhQKoNGjhhkWfIgWocLu8_APJul3cDS9gvykuQ",
    "link": "http://www.myntra.com/Toner/THE+ORDINARY/THE-ORDINARY-Glycolic-Acid-7-Exfoliating-Toner---100ml/33061355/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-luxe-ajio-com-3-the-ordinary-glycolic-acid-7-toning-solution",
    "title": "The Ordinary Glycolic Acid 7% Toning Solution",
    "store": "luxe.ajio.com",
    "domain": "luxe.ajio.com",
    "price": "₹900",
    "numericPrice": 900,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYHrNPhlRDuhMx0UlYi1IWGwPSYw8b1ZAKxvrCnj6JJWwivikSyacBYlTfrqCa2i9JRIDMZSTPra1LQrptWhQKoNGjhhkWfIgWocLu8_APJul3cDS9gvykuQ",
    "link": "https://luxe.ajio.com/the-ordinary-glycolic-acid-7-exfoliating-toner/p/4944746560_multi#gmf",
    "availability": "Current listing on luxe.ajio.com",
    "sourceType": "text"
  },
  {
    "id": "preload-mamaearth-in-0-mamaearth-ubtan-face-wash",
    "title": "Mamaearth Ubtan Face Wash",
    "store": "Mamaearth",
    "domain": "mamaearth.in",
    "price": "₹428",
    "numericPrice": 428,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlcheIMTy7mpLg2WnB4uItYu8eiIE1CTEltYuGDpJJfgZct2XomDTA-u2KLtgJZDT18c1442IekXOCFyjnJNqYV0YKBC5Wv5Brz3lqdGqx4E_cxRHI_AZAfEAH",
    "link": "https://mamaearth.in/products/ubtan-facewash-for-tan-removal-pack-of-2?srsltid=AfmBOooNTG8trfCEwE3pDGfwsCENW3BHOoLf209Ln_dL_mkEpMQB4QkOa7s",
    "availability": "Current listing on Mamaearth",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-mamaearth-ubtan-face-wash",
    "title": "Mamaearth Ubtan Face Wash",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹245",
    "numericPrice": 245,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlcheIMTy7mpLg2WnB4uItYu8eiIE1CTEltYuGDpJJfgZct2XomDTA-u2KLtgJZDT18c1442IekXOCFyjnJNqYV0YKBC5Wv5Brz3lqdGqx4E_cxRHI_AZAfEAH",
    "link": "https://www.flipkart.com/mamaearth-ubtan-natural-dry-skin-turmeric-saffron-tan-removal-brightning-sls-paraben-free-face-wash/p/itm2caaeaf8e5a37",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-2-mamaearth-ubtan-face-wash",
    "title": "Mamaearth Ubtan Face Wash",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹399",
    "numericPrice": 399,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRlcheIMTy7mpLg2WnB4uItYu8eiIE1CTEltYuGDpJJfgZct2XomDTA-u2KLtgJZDT18c1442IekXOCFyjnJNqYV0YKBC5Wv5Brz3lqdGqx4E_cxRHI_AZAfEAH",
    "link": "https://www.amazon.in/Mamaearth-Natural-Turmeric-Saffron-Brightening/dp/B0BJ6L6KMN?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A61C6NUFGVGS7",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-0-plum-green-tea-toner",
    "title": "Plum Green Tea Toner",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹331",
    "numericPrice": 331,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzMDSHJxxLxWFXLOa2lkbFO_9PvRK2UXICPtXLYyJKMKo6bW6e_PDG3X5gA7bHY4Nis7DCqIc1m7fwhTS57mEnnFCZIp8WQahNjuMiCIo6ImnTs0ojfPXM",
    "link": "http://www.myntra.com/Toner/Plum/Plum-Green-Tea-Alcohol-Free-Face-Toner--150ml/30904616/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-tirabeauty-com-1-plum-green-tea-toner",
    "title": "Plum Green Tea Toner",
    "store": "Tira",
    "domain": "tirabeauty.com",
    "price": "₹331",
    "numericPrice": 331,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzMDSHJxxLxWFXLOa2lkbFO_9PvRK2UXICPtXLYyJKMKo6bW6e_PDG3X5gA7bHY4Nis7DCqIc1m7fwhTS57mEnnFCZIp8WQahNjuMiCIo6ImnTs0ojfPXM",
    "link": "https://www.tirabeauty.com/product/plum-green-tea-alcohol-free-face-toner-for-oily-acneprone-skin-glycolic-acid-fights-pimples-150-ml-7607937?srsltid=AfmBOoqgbfZwdXTi0LsKZ_ICqNUpC4Kzko36b3MBDVbkjhNieCMA9r7DS-w",
    "availability": "Current listing on Tira",
    "sourceType": "text"
  },
  {
    "id": "preload-nykaa-com-2-plum-green-tea-toner",
    "title": "Plum Green Tea Toner",
    "store": "nykaa.com",
    "domain": "nykaa.com",
    "price": "₹332",
    "numericPrice": 332,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzMDSHJxxLxWFXLOa2lkbFO_9PvRK2UXICPtXLYyJKMKo6bW6e_PDG3X5gA7bHY4Nis7DCqIc1m7fwhTS57mEnnFCZIp8WQahNjuMiCIo6ImnTs0ojfPXM",
    "link": "https://www.nykaa.com/plum-green-tea-alcohol-free-face-toner/p/16936458",
    "availability": "Current listing on nykaa.com",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-3-plum-green-tea-toner",
    "title": "Plum Green Tea Toner",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹357",
    "numericPrice": 357,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzMDSHJxxLxWFXLOa2lkbFO_9PvRK2UXICPtXLYyJKMKo6bW6e_PDG3X5gA7bHY4Nis7DCqIc1m7fwhTS57mEnnFCZIp8WQahNjuMiCIo6ImnTs0ojfPXM",
    "link": "https://www.amazon.in/Plum-Green-Alcohol-Toner-200ml/dp/B00OCJ5M6C?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1PDPV3K0BFW6T",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-0-nike-dri-fit-t-shirt",
    "title": "Nike Dri-FIT T-Shirt",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹1,196",
    "numericPrice": 1196,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSUdf00U9JNatnkq_qNTlkwOHFlrDwjkSLBsUwsVQlThK5zhYD8R-Zo-T2ek9n4N6qLMuLaB820SGUju0GXoVS_Oi51dgOHvLtPJ8qp7xBnTVI8DeO779NoqA",
    "link": "http://www.myntra.com/Tshirts/Nike/Nike-Pro-Men-Dri-FIT-Tight-Short-Sleeve-Fitness-T-Shirt/40884487/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-nike-dri-fit-t-shirt",
    "title": "Nike Dri-FIT T-Shirt",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹1,196",
    "numericPrice": 1196,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSUdf00U9JNatnkq_qNTlkwOHFlrDwjkSLBsUwsVQlThK5zhYD8R-Zo-T2ek9n4N6qLMuLaB820SGUju0GXoVS_Oi51dgOHvLtPJ8qp7xBnTVI8DeO779NoqA",
    "link": "https://www.amazon.in/Nike-FB7933-398-Mens-Dri-FIT-Top/dp/B0GSGRQ2RC?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A2O5KR0Y95DC4B",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-adidas-co-in-0-adidas-essentials-hoodie",
    "title": "Adidas Essentials Hoodie",
    "store": "adidas.co.in",
    "domain": "adidas.co.in",
    "price": "₹1,999.50",
    "numericPrice": 1999.5,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRtqnKPseLDQcqjpDxNKgqFWhZKKx3wXjAd4kJAopwvpygTe5FC8_GmGqKTZXiVn26DMcWP7ElE2u7e4NJoF3IvBHIfhPDL",
    "link": "https://www.adidas.co.in/essentials-fleece-hoodie/H12213.html",
    "availability": "Current listing on adidas.co.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-1-adidas-essentials-hoodie",
    "title": "Adidas Essentials Hoodie",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹1,599",
    "numericPrice": 1599,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRtqnKPseLDQcqjpDxNKgqFWhZKKx3wXjAd4kJAopwvpygTe5FC8_GmGqKTZXiVn26DMcWP7ElE2u7e4NJoF3IvBHIfhPDL",
    "link": "http://www.myntra.com/Sweatshirts/ADIDAS/ADIDAS-Men-Hooded-Sweatshirt/23697532/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-2-adidas-essentials-hoodie",
    "title": "Adidas Essentials Hoodie",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹1,907",
    "numericPrice": 1907,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRtqnKPseLDQcqjpDxNKgqFWhZKKx3wXjAd4kJAopwvpygTe5FC8_GmGqKTZXiVn26DMcWP7ElE2u7e4NJoF3IvBHIfhPDL",
    "link": "https://www.amazon.in/Adidas-Cotton-Hooded-Sweatshirt-H12213_MGREYH/dp/B096G9PJ3G?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A21RDF1QS3FX7F",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-in-puma-com-0-puma-smashic-sneakers",
    "title": "Puma Smashic Sneakers",
    "store": "PUMA India",
    "domain": "in.puma.com",
    "price": "₹1,934",
    "numericPrice": 1934,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRE5tCyk-ydclo4MkfGZlqI-ePouOj9ySvSZpkHikNQi-0I6a-nuDmaMaITDP8GA__QI5Zyh7iS46q4omDEB6b1kHbJzody-660yrIdva7dGmpfHurAaohOUmg",
    "link": "https://in.puma.com/in/en/pd/smashic-comfort-casual-sneakers/394371?size=0240&swatch=01&srsltid=AfmBOooZyiHZjnkqtrfM4C4ljUVfjQe2ibnlZt9KvWlk8aLToDlUFAaWoJA",
    "availability": "Current listing on PUMA India",
    "sourceType": "text"
  },
  {
    "id": "preload-ajio-com-1-puma-smashic-sneakers",
    "title": "Puma Smashic Sneakers",
    "store": "ajio.com",
    "domain": "ajio.com",
    "price": "₹1,665",
    "numericPrice": 1665,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRE5tCyk-ydclo4MkfGZlqI-ePouOj9ySvSZpkHikNQi-0I6a-nuDmaMaITDP8GA__QI5Zyh7iS46q4omDEB6b1kHbJzody-660yrIdva7dGmpfHurAaohOUmg",
    "link": "https://www.ajio.com/puma-smashic-comfort-casual-sneakers/p/465642484002",
    "availability": "Current listing on ajio.com",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-2-puma-smashic-sneakers",
    "title": "Puma Smashic Sneakers",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹1,799",
    "numericPrice": 1799,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRE5tCyk-ydclo4MkfGZlqI-ePouOj9ySvSZpkHikNQi-0I6a-nuDmaMaITDP8GA__QI5Zyh7iS46q4omDEB6b1kHbJzody-660yrIdva7dGmpfHurAaohOUmg",
    "link": "http://www.myntra.com/Casual-Shoes/Puma/Puma-Smashic-Comfort-Casual-Sneakers/21767158/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-tatacliq-com-3-puma-smashic-sneakers",
    "title": "Puma Smashic Sneakers",
    "store": "tatacliq.com",
    "domain": "tatacliq.com",
    "price": "₹1,799",
    "numericPrice": 1799,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRE5tCyk-ydclo4MkfGZlqI-ePouOj9ySvSZpkHikNQi-0I6a-nuDmaMaITDP8GA__QI5Zyh7iS46q4omDEB6b1kHbJzody-660yrIdva7dGmpfHurAaohOUmg",
    "link": "https://www.tatacliq.com/puma-mens-smashic-black-casual-sneakers/p-mp000000016283439",
    "availability": "Current listing on tatacliq.com",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-0-h-m-cotton-shirt",
    "title": "H&M Cotton Shirt",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹499",
    "numericPrice": 499,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRocYTfJ0ax_sKKWRsYPVAFPzoNJyVcFMr4UWaK3w1MDUTdnuo7XR-rmUC1E1x8f5siXagBuV8O00nv7Jz1x0eLusla7pnyqNyfYKlUDUGoJ56oAFg_3k_u",
    "link": "http://www.myntra.com/Tshirts/H%26M/HM-Men-Grey-Solid-Round-neck-T-shirt-Regular-Fit/12155048/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-nykaafashion-com-1-h-m-cotton-shirt",
    "title": "H&M Cotton Shirt",
    "store": "Nykaa Fashion",
    "domain": "nykaafashion.com",
    "price": "₹598.10",
    "numericPrice": 598.1,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRocYTfJ0ax_sKKWRsYPVAFPzoNJyVcFMr4UWaK3w1MDUTdnuo7XR-rmUC1E1x8f5siXagBuV8O00nv7Jz1x0eLusla7pnyqNyfYKlUDUGoJ56oAFg_3k_u",
    "link": "https://www.nykaafashion.com/h-m-regular-fit-round-neck-t-shirt-grey/p/23077881?adsource=shopping_india&skuId=23067437&srsltid=AfmBOopzvOxhK8kEEzKTFIbsQPo067R-VJMOQrNh9Mda3s0-du3jaygP2vc",
    "availability": "Current listing on Nykaa Fashion",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-0-roadster-men-black-jeans",
    "title": "Roadster Men Black Jeans",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹671",
    "numericPrice": 671,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTZmoByJFkneLtyXLcLW3ttyvFjW0cW3M1y7fGyXtPnBT--NXJtZn6KZR3y3kj0KKrzD9vHk-ypkvEAkmxvkXcNusF0cuGi16asYc7vOVLzvCpbN4R8tIREkA",
    "link": "http://www.myntra.com/Jeans/Roadster/The-Roadster-Lifestyle-Co-Men-Bootcut-Light-Fade-Stretchable-Jeans/24827776/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-1-roadster-men-black-jeans",
    "title": "Roadster Men Black Jeans",
    "store": "Myntra - MNow",
    "domain": "myntra.com",
    "price": "₹671",
    "numericPrice": 671,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTZmoByJFkneLtyXLcLW3ttyvFjW0cW3M1y7fGyXtPnBT--NXJtZn6KZR3y3kj0KKrzD9vHk-ypkvEAkmxvkXcNusF0cuGi16asYc7vOVLzvCpbN4R8tIREkA",
    "link": "http://www.myntra.com/Jeans/Roadster/The-Roadster-Lifestyle-Co-Men-Bootcut-Light-Fade-Stretchable-Jeans/24827776/buy",
    "availability": "Current listing on Myntra - MNow",
    "sourceType": "text"
  },
  {
    "id": "preload-biba-in-0-biba-printed-kurta",
    "title": "Biba Printed Kurta",
    "store": "Biba.in",
    "domain": "biba.in",
    "price": "₹1,000",
    "numericPrice": 1000,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSqiIloK1rtL6zOuP6tOkFpgMrivmJd9erLEAtfgvkshiRHpua6N-GlY74WBQRQu3YOzi2vEXFdMI0-jT1kUSOil6JowGVMMO97yXCpWnEE",
    "link": "https://biba.in/in/rust-cotton-printed-straight-kurta/8905641817791.html?nbsp=true",
    "availability": "Current listing on Biba.in",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-biba-printed-kurta",
    "title": "Biba Printed Kurta",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹819",
    "numericPrice": 819,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSqiIloK1rtL6zOuP6tOkFpgMrivmJd9erLEAtfgvkshiRHpua6N-GlY74WBQRQu3YOzi2vEXFdMI0-jT1kUSOil6JowGVMMO97yXCpWnEE",
    "link": "https://www.amazon.in/Biba-Women-Rust-Cotton-Kurta_46/dp/B0F669SQCV?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1WYWER0W24N8S",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-tatacliq-com-2-biba-printed-kurta",
    "title": "Biba Printed Kurta",
    "store": "tatacliq.com",
    "domain": "tatacliq.com",
    "price": "₹999",
    "numericPrice": 999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSqiIloK1rtL6zOuP6tOkFpgMrivmJd9erLEAtfgvkshiRHpua6N-GlY74WBQRQu3YOzi2vEXFdMI0-jT1kUSOil6JowGVMMO97yXCpWnEE",
    "link": "https://www.tatacliq.com/biba-rust-printed-straight-kurta/p-mp000000023314435",
    "availability": "Current listing on tatacliq.com",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-3-biba-printed-kurta",
    "title": "Biba Printed Kurta",
    "store": "Myntra",
    "domain": "myntra.com",
    "price": "₹1,999",
    "numericPrice": 1999,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSqiIloK1rtL6zOuP6tOkFpgMrivmJd9erLEAtfgvkshiRHpua6N-GlY74WBQRQu3YOzi2vEXFdMI0-jT1kUSOil6JowGVMMO97yXCpWnEE",
    "link": "http://www.myntra.com/Kurtas/Biba/Biba-Women-Ethnic-Motifs-Printed-Kurta/34024953/buy",
    "availability": "Current listing on Myntra",
    "sourceType": "text"
  },
  {
    "id": "preload-brandstik-com-0-boat-stone-650-bluetooth-speaker",
    "title": "boAt Stone 650 Bluetooth Speaker",
    "store": "BrandStik",
    "domain": "brandstik.com",
    "price": "₹5,000",
    "numericPrice": 5000,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx0Sjcomhx2CoJjrso09Yd3Y5piLdX6qacu6x0BCdmVx5o5xtJCYx4P0VZgfGjWXTKFDocMjwEvRvMGu4U0bULF8nZ-lz1N3dSaDlpGqk6sQ3ljJXiU4fwEQ",
    "link": "https://www.brandstik.com/shop/products/boat-stone-600-speakers?srsltid=AfmBOorVeUoILskjnw-yYSZCMwcQSgbi7bRLR_R7s9KenibmSPGXRb2ELks",
    "availability": "Current listing on BrandStik",
    "sourceType": "text"
  },
  {
    "id": "preload-soundbybroot-com-1-boat-stone-650-bluetooth-speaker",
    "title": "boAt Stone 650 Bluetooth Speaker",
    "store": "soundbybroot.com",
    "domain": "soundbybroot.com",
    "price": "₹1,995",
    "numericPrice": 1995,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx0Sjcomhx2CoJjrso09Yd3Y5piLdX6qacu6x0BCdmVx5o5xtJCYx4P0VZgfGjWXTKFDocMjwEvRvMGu4U0bULF8nZ-lz1N3dSaDlpGqk6sQ3ljJXiU4fwEQ",
    "link": "https://soundbybroot.com/products/boat-bluetooth-speaker-stone-600",
    "availability": "Current listing on soundbybroot.com",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-boat-stone-650-bluetooth-speaker",
    "title": "boAt Stone 650 Bluetooth Speaker",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹2,499",
    "numericPrice": 2499,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRx0Sjcomhx2CoJjrso09Yd3Y5piLdX6qacu6x0BCdmVx5o5xtJCYx4P0VZgfGjWXTKFDocMjwEvRvMGu4U0bULF8nZ-lz1N3dSaDlpGqk6sQ3ljJXiU4fwEQ",
    "link": "https://www.flipkart.com/boat-600-water-proof-10-w-portable-bluetooth-speaker/p/itmep5e438k3zspx?pid=ACCEP5E4RGTM9F2H&lid=LSTACCEP5E4RGTM9F2HBNUU1E&marketplace=FLIPKART&cmpid=content_speaker_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-logitech-m350-pebble-mouse",
    "title": "Logitech M350 Pebble Mouse",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹1,595",
    "numericPrice": 1595,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQt9_nhekC2V706gzsndCqFAMMqmD8UqlKzdvpq16OochY3SvFu_D3r0dvTcsuDAxCxDK7wZtirR1Tbgs1yfRg4GLOS74JI8TxdQAwtwY3u9w5pLQbhWKSYf8I",
    "link": "https://www.amazon.in/Logitech-Bluetooth-Lightweight-Customisable-Easy-Switch/dp/B0CGCZHGW1?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AJ6SIZC8YQDZX",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-logitech-m350-pebble-mouse",
    "title": "Logitech M350 Pebble Mouse",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹1,499",
    "numericPrice": 1499,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQt9_nhekC2V706gzsndCqFAMMqmD8UqlKzdvpq16OochY3SvFu_D3r0dvTcsuDAxCxDK7wZtirR1Tbgs1yfRg4GLOS74JI8TxdQAwtwY3u9w5pLQbhWKSYf8I",
    "link": "https://www.flipkart.com/logitech-pebble-2-m350s-wireless-ambidextrous-optical-mouse-4000-dpi-quiet-clicks-cross-os-easy-switch/p/itm92cb79bba13d0?pid=ACCGSZ6YTMHTZAR2&lid=LSTACCGSZ6YTMHTZAR2EFACKN&marketplace=FLIPKART&cmpid=content_mouse_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-deltapage-com-2-logitech-m350-pebble-mouse",
    "title": "Logitech M350 Pebble Mouse",
    "store": "Delta Peripherals",
    "domain": "deltapage.com",
    "price": "₹1,750",
    "numericPrice": 1750,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQt9_nhekC2V706gzsndCqFAMMqmD8UqlKzdvpq16OochY3SvFu_D3r0dvTcsuDAxCxDK7wZtirR1Tbgs1yfRg4GLOS74JI8TxdQAwtwY3u9w5pLQbhWKSYf8I",
    "link": "https://www.deltapage.com/shop/logitech-pebble-mouse-2-m350s-bluetooth-8086?page=2&srsltid=AfmBOooOGmel5ky3SWnPZDCtihZUhN0nYUltr1rhaJ1qoVivKXSo67kSiQM",
    "availability": "Current listing on Delta Peripherals",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-hp-k500f-gaming-keyboard",
    "title": "HP K500F Gaming Keyboard",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹1,349",
    "numericPrice": 1349,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcROscM0L5SkNmSM9cikHoyROiFn40ux10aQXYuYioZsT-YVoQzWnrQeAKmIL16eOhubNVr2pSaNKX0dv35wgDsio16vTLrCY5CJX1pPMWx1R2_YyYN0OWDgSac",
    "link": "https://www.amazon.in/HP-K500F-Gaming-Keyboard-7ZZ97AA/dp/B08498D67S?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AJ6SIZC8YQDZX",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-electroconnect-in-1-hp-k500f-gaming-keyboard",
    "title": "HP K500F Gaming Keyboard",
    "store": "ElectroConnect",
    "domain": "electroconnect.in",
    "price": "₹1,149",
    "numericPrice": 1149,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcROscM0L5SkNmSM9cikHoyROiFn40ux10aQXYuYioZsT-YVoQzWnrQeAKmIL16eOhubNVr2pSaNKX0dv35wgDsio16vTLrCY5CJX1pPMWx1R2_YyYN0OWDgSac",
    "link": "https://electroconnect.in/hp-k500f-wired-gaming-keyboard-backlit-membrane-with-mixed-color-lighting-metal",
    "availability": "Current listing on ElectroConnect",
    "sourceType": "text"
  },
  {
    "id": "preload-vlebazaar-in-0-samsung-galaxy-m35-5g",
    "title": "Samsung Galaxy M35 5G",
    "store": "vlebazaar.in",
    "domain": "vlebazaar.in",
    "price": "₹13,799",
    "numericPrice": 13799,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2s9Wdo61RjEBgQAkT6CW_QuZS-Br66No-lqiSDU-iG5jJaMOWQjFr2z_ylYrdlbUcsRFZ5XqqRxlJvy4LxhMC4xTnkFiwujKtMYg40hr5XwIB4Co9O3ie",
    "link": "https://vlebazaar.in/Samsung-Galaxy-M35-5G-Moonlight-Blue6GB-RAM128GB-Storage-Corning-Gorilla-Glass-V_1?srsltid=AfmBOoq85EG0W0u1mREEMgND7qyiwvfvA-Tzc6FO5oi_7Tu59iuhGRYFiMc",
    "availability": "Current listing on vlebazaar.in",
    "sourceType": "text"
  },
  {
    "id": "preload-poojaratele-com-1-samsung-galaxy-m35-5g",
    "title": "Samsung Galaxy M35 5G",
    "store": "Poojara Telecom",
    "domain": "poojaratele.com",
    "price": "₹19,999",
    "numericPrice": 19999,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2s9Wdo61RjEBgQAkT6CW_QuZS-Br66No-lqiSDU-iG5jJaMOWQjFr2z_ylYrdlbUcsRFZ5XqqRxlJvy4LxhMC4xTnkFiwujKtMYg40hr5XwIB4Co9O3ie",
    "link": "https://www.poojaratele.com/product/samsung-m35-5g-moonlight-blue-6gb-+-128-gb?srsltid=AfmBOop9l3lgeKnwmsjjulra17eONAuzDiZPw2PFZsbv7lIG45ka2qlUTrw",
    "availability": "Current listing on Poojara Telecom",
    "sourceType": "text"
  },
  {
    "id": "preload-triveniworld-com-2-samsung-galaxy-m35-5g",
    "title": "Samsung Galaxy M35 5G",
    "store": "Triveni World",
    "domain": "triveniworld.com",
    "price": "₹9,999",
    "numericPrice": 9999,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2s9Wdo61RjEBgQAkT6CW_QuZS-Br66No-lqiSDU-iG5jJaMOWQjFr2z_ylYrdlbUcsRFZ5XqqRxlJvy4LxhMC4xTnkFiwujKtMYg40hr5XwIB4Co9O3ie",
    "link": "https://www.triveniworld.com/products/samsung-galaxy-m35-5g-moonlight-blue-6gb-ram-128gb-storage-corning-gorilla-glass-victus-antutu-score-595k-vapour-cooling-chamber-6000mah-battery-120hz-super-amoled-display-without-charger?currency=INR&country=IN&country=IN&variant=49071176384809&utm_source=google&utm_medium=cpc&utm_campaign=Google%20Shopping&stkn=7b73ea27af9f&srsltid=AfmBOooRGyTG-Xtg-ZxMdp6LIewAlTGoxu2fChsXDXL7ntRuuiL-bfJBuso",
    "availability": "Current listing on Triveni World",
    "sourceType": "text"
  },
  {
    "id": "preload-cashify-in-0-apple-iphone-15",
    "title": "Apple iPhone 15",
    "store": "Cashify",
    "domain": "cashify.in",
    "price": "₹46,299",
    "numericPrice": 46299,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQMq-YgAGgelcMzS3o8wpCwY8y8wED8hN64ICBnvYQCITw8l9X3oseak02zRRfdWLpfHnhZgXIY7jayBzZUrRF6abbK2XGJsTt3JD6GSuQJ7QPAaxo7iWI2Tpux",
    "link": "https://www.cashify.in/buy-refurbished-mobile-phones/renewed-apple-iphone-15/225478?srsltid=AfmBOoqaY7mGXze95YYPBIAcvpO9fSubP8IuricO3qXt26YH0RaleLj15Hw",
    "availability": "Current listing on Cashify",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-1-apple-iphone-15",
    "title": "Apple iPhone 15",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹59,900",
    "numericPrice": 59900,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQMq-YgAGgelcMzS3o8wpCwY8y8wED8hN64ICBnvYQCITw8l9X3oseak02zRRfdWLpfHnhZgXIY7jayBzZUrRF6abbK2XGJsTt3JD6GSuQJ7QPAaxo7iWI2Tpux",
    "link": "https://www.flipkart.com/apple-iphone-15-black-128-gb/p/itm6ac6485515ae4?pid=MOBGTAGPTB3VS24W&lid=LSTMOBGTAGPTB3VS24WKFODHL&marketplace=FLIPKART&cmpid=content_mobile_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-2-apple-iphone-15",
    "title": "Apple iPhone 15",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹56,900",
    "numericPrice": 56900,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQMq-YgAGgelcMzS3o8wpCwY8y8wED8hN64ICBnvYQCITw8l9X3oseak02zRRfdWLpfHnhZgXIY7jayBzZUrRF6abbK2XGJsTt3JD6GSuQJ7QPAaxo7iWI2Tpux",
    "link": "https://www.zepto.com/pn/apple-iphone-15-128-gb-black/pvid/b55bdb12-5f54-4b13-9bb8-7fb7d8818b0e?srsltid=AfmBOopJF6UpBfRSXs88_6me1syu9lc06JnD5tsOMhjfkQ3gkfCyamsD8Ng",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-0-oneplus-nord-ce4",
    "title": "OnePlus Nord CE4",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹16,657",
    "numericPrice": 16657,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRN5Zl0722lBY1rSNkywcXLddDVGm0uMvP7f-zBjq7kMxVn4SDLtuUwq3yTdKXOJ392YRKGxOQqiM95-D3_EHKR__Hz8SLG-Y-egsKHWG6qR8BKyh2SjPinDg",
    "link": "https://www.zepto.com/pn/oneplus-nord-ce4-8gb-128gb-dark-chrome/pvid/a5d53510-b989-48d5-ba40-9cbd2242aca0?srsltid=AfmBOorw0rIa3bW9p_QcTmWRjmtb7SIZ7t7YoA6a3a4ns42QW85HlXAkWrA",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-mobilekidukaan-in-1-oneplus-nord-ce4",
    "title": "OnePlus Nord CE4",
    "store": "Mobile Ki Dukaan",
    "domain": "mobilekidukaan.in",
    "price": "₹22,999",
    "numericPrice": 22999,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRN5Zl0722lBY1rSNkywcXLddDVGm0uMvP7f-zBjq7kMxVn4SDLtuUwq3yTdKXOJ392YRKGxOQqiM95-D3_EHKR__Hz8SLG-Y-egsKHWG6qR8BKyh2SjPinDg",
    "link": "https://mobilekidukaan.in/buy-mobile-phones-oneplus/oneplus-nord-ce4?srsltid=AfmBOoovt-jNPhTa-LznF4bKhYUcbuQnJZDck01VD5TkmJ2St-8aVrPjTOQ",
    "availability": "Current listing on Mobile Ki Dukaan",
    "sourceType": "text"
  },
  {
    "id": "preload-sell-gameloot-in-2-oneplus-nord-ce4",
    "title": "OnePlus Nord CE4",
    "store": "GameLoot",
    "domain": "sell.gameloot.in",
    "price": "₹8,000",
    "numericPrice": 8000,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRN5Zl0722lBY1rSNkywcXLddDVGm0uMvP7f-zBjq7kMxVn4SDLtuUwq3yTdKXOJ392YRKGxOQqiM95-D3_EHKR__Hz8SLG-Y-egsKHWG6qR8BKyh2SjPinDg",
    "link": "https://sell.gameloot.in/shop/oneplus-nord-ce-4-8gb-ram-128gb-storage-color/",
    "availability": "Current listing on GameLoot",
    "sourceType": "text"
  },
  {
    "id": "preload-soundbybroot-com-0-kindle-paperwhite",
    "title": "Kindle Paperwhite",
    "store": "soundbybroot.com",
    "domain": "soundbybroot.com",
    "price": "₹17,999",
    "numericPrice": 17999,
    "image": "https://soundbybroot.com/cdn/shop/products/515Z2glAStL._SL1000_grande.jpg?v=1643793025",
    "link": "https://soundbybroot.com/products/amazon-kindle-e-reader-paperwhite-10th-gen-with-built-in-light-waterproof-32-gb-wifi-free-4g-lte",
    "availability": "Current listing on soundbybroot.com",
    "sourceType": "text"
  },
  {
    "id": "preload-sell-gameloot-in-1-kindle-paperwhite",
    "title": "Kindle Paperwhite",
    "store": "GameLoot",
    "domain": "sell.gameloot.in",
    "price": "₹3,500",
    "numericPrice": 3500,
    "image": "https://soundbybroot.com/cdn/shop/products/515Z2glAStL._SL1000_grande.jpg?v=1643793025",
    "link": "https://sell.gameloot.in/shop/amazon-kindle-paperwhite-4-10th-gen-32-gb-wifi-lte-any-color/",
    "availability": "Current listing on GameLoot",
    "sourceType": "text"
  },
  {
    "id": "preload-nykaafashion-com-2-kindle-paperwhite",
    "title": "Kindle Paperwhite",
    "store": "Nykaa Fashion",
    "domain": "nykaafashion.com",
    "price": "₹17,999",
    "numericPrice": 17999,
    "image": "https://soundbybroot.com/cdn/shop/products/515Z2glAStL._SL1000_grande.jpg?v=1643793025",
    "link": "https://www.nykaafashion.com/amazon-kindle-paperwhite-10th-gen-with-built-in-light-waterproof-32-gb-wifi-free-4g-lte/p/2844567?srsltid=AfmBOoq-1PfV2H2APpgOcml4qmSqcZNsPgV1iUuAR3gOR87FQkfR6G4TgQI",
    "availability": "Current listing on Nykaa Fashion",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-faber-castell-brush-pens",
    "title": "Faber-Castell Brush Pens",
    "store": "amazon.in",
    "domain": "amazon.in",
    "price": "₹160",
    "numericPrice": 160,
    "image": "https://m.media-amazon.com/images/I/61imaGDpJhL.jpg",
    "link": "https://www.amazon.in/8-90E-12-Faber-castell-Connector-Pens/dp/B00VBHJBMY",
    "availability": "Current listing on amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-beetlekrafts-com-1-faber-castell-brush-pens",
    "title": "Faber-Castell Brush Pens",
    "store": "Beetle Krafts",
    "domain": "beetlekrafts.com",
    "price": "₹72",
    "numericPrice": 72,
    "image": "https://m.media-amazon.com/images/I/61imaGDpJhL.jpg",
    "link": "https://beetlekrafts.com/product/faber-castell-15-connector-pens-washable-vibrant-non-toxic/?srsltid=AfmBOoo7ooSF8dTq_yuzWQmBZ8dViVPMHauvELtK83UTOzglBECOcHSwkMc",
    "availability": "Current listing on Beetle Krafts",
    "sourceType": "text"
  },
  {
    "id": "preload-canvazo-com-2-faber-castell-brush-pens",
    "title": "Faber-Castell Brush Pens",
    "store": "Canvazo",
    "domain": "canvazo.com",
    "price": "₹180",
    "numericPrice": 180,
    "image": "https://m.media-amazon.com/images/I/61imaGDpJhL.jpg",
    "link": "https://canvazo.com/products/faber-castell-connector-brush-pen-sets?variant=46101659222251&country=IN&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOoouTq2k_jEo0okLPUQJeR24qPaEYmv-tWmYrSWxdxzXdimirn-7baM",
    "availability": "Current listing on Canvazo",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-0-classmate-pulse-notebook",
    "title": "Classmate Pulse Notebook",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹115",
    "numericPrice": 115,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2I5w8cowilZv4MT9XwgX2cx6fFBWROlvX9sjUzByR6aBVGFfDrQf4SJSyUyI3BpBwspWWAPEAdJbdRWvQvnbidfINWlfMGg",
    "link": "http://www.flipkart.com/classmate-pulse-book-size-notebook-unruled-300-pages/p/itmfgycs9epagjay?pid=DIAFGYCS9H7YJ8QT&lid=LSTDIAFGYCS9H7YJ8QTM7WZZ2&marketplace=HYPERLOCAL&cmpid=content_diary-notebook_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-1-classmate-pulse-notebook",
    "title": "Classmate Pulse Notebook",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹129",
    "numericPrice": 129,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2I5w8cowilZv4MT9XwgX2cx6fFBWROlvX9sjUzByR6aBVGFfDrQf4SJSyUyI3BpBwspWWAPEAdJbdRWvQvnbidfINWlfMGg",
    "link": "https://www.zepto.com/pn/classmate-pulse-spiral-notebook-6-sub-unruled-b5-240-x-180-302pgs/pvid/d82ac5c6-a8ec-4364-90af-83fd9b41498e?srsltid=AfmBOooMIMvBJeeqa3Eqn88H05OnAZhRm1w0bdkLpA-jPLyPQeg2QuPgQn8",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-blinkit-com-2-classmate-pulse-notebook",
    "title": "Classmate Pulse Notebook",
    "store": "Blinkit",
    "domain": "blinkit.com",
    "price": "₹135",
    "numericPrice": 135,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2I5w8cowilZv4MT9XwgX2cx6fFBWROlvX9sjUzByR6aBVGFfDrQf4SJSyUyI3BpBwspWWAPEAdJbdRWvQvnbidfINWlfMGg",
    "link": "https://blinkit.com/prn/classmate-pulse-6-subject-notebook-multicolour-1-pc/prid/429676?catalogue_source=google_mca_5700965956&srsltid=AfmBOorldJIMXMhhkAzLQ7QZeYKClVSQZ5nnomtYA7mjZPV5t1LPxY8ZDT0&region_id=37874",
    "availability": "Current listing on Blinkit",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-3-classmate-pulse-notebook",
    "title": "Classmate Pulse Notebook",
    "store": "amazon.in",
    "domain": "amazon.in",
    "price": "₹240",
    "numericPrice": 240,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT2I5w8cowilZv4MT9XwgX2cx6fFBWROlvX9sjUzByR6aBVGFfDrQf4SJSyUyI3BpBwspWWAPEAdJbdRWvQvnbidfINWlfMGg",
    "link": "https://www.amazon.in/Classmate-Pulse-Spiral-Notebook-Unruled/dp/B00P93X0VO",
    "availability": "Current listing on amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-0-post-it-sticky-notes",
    "title": "Post-it Sticky Notes",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹85",
    "numericPrice": 85,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ_dg890RlrWDBfQGY_TiWenhwanTP4dmXxqY61mIoz-_Kgsakb8r-6p_1fx2Vb0miizmcoB3mrskls06Y9ui4v0x8rwEhK1zUkziODPfSGMUinAdrtWjXqoOU",
    "link": "https://www.zepto.com/pn/post-it-sticky-notes-pad-3inch-x-3inch-100-notes-assorted/pvid/018a4631-2ec1-4f42-9fbb-bf51838eef65?srsltid=AfmBOoroK_dHWrLMXQOsRu-ENtGH0oucjEjfrVvz-Kebd6aYm0k4Ury_W20",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-scooboo-in-1-post-it-sticky-notes",
    "title": "Post-it Sticky Notes",
    "store": "Scooboo",
    "domain": "scooboo.in",
    "price": "₹66.50",
    "numericPrice": 66.5,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ_dg890RlrWDBfQGY_TiWenhwanTP4dmXxqY61mIoz-_Kgsakb8r-6p_1fx2Vb0miizmcoB3mrskls06Y9ui4v0x8rwEhK1zUkziODPfSGMUinAdrtWjXqoOU",
    "link": "https://scooboo.in/products/post-it-sticky-notepad-1?variant=42016400408631&country=IN&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOop-iukjD5EyP62FbqPygT5e2eX15MmQ-BTYgyY-xXRsxAhSE7wbk1U",
    "availability": "Current listing on Scooboo",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-post-it-sticky-notes",
    "title": "Post-it Sticky Notes",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹70",
    "numericPrice": 70,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ_dg890RlrWDBfQGY_TiWenhwanTP4dmXxqY61mIoz-_Kgsakb8r-6p_1fx2Vb0miizmcoB3mrskls06Y9ui4v0x8rwEhK1zUkziODPfSGMUinAdrtWjXqoOU",
    "link": "https://www.flipkart.com/post-it-sticky-notes-self-adhesive-100-sheets-standard-notes-6-colors/p/itm3d375c1faf3f9?pid=PSIHD5VZCEGRR8MK&lid=LSTPSIHD5VZCEGRR8MKWWUQYK&hl_lid=&marketplace=HYPERLOCAL&fm=eyJ3dHAiOiJyZWNvIiwicHJwdCI6InBwIiwibWlkIjoicHJvZHVjdFJlY29tbWVuZGF0aW9uL2Nyb3NzU2VsbGluZyJ9",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-3-post-it-sticky-notes",
    "title": "Post-it Sticky Notes",
    "store": "amazon.in",
    "domain": "amazon.in",
    "price": "₹115",
    "numericPrice": 115,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQ_dg890RlrWDBfQGY_TiWenhwanTP4dmXxqY61mIoz-_Kgsakb8r-6p_1fx2Vb0miizmcoB3mrskls06Y9ui4v0x8rwEhK1zUkziODPfSGMUinAdrtWjXqoOU",
    "link": "https://www.amazon.in/Post-Sticky-Notes-Sheets-inches/dp/B00N1U7D60",
    "availability": "Current listing on amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-0-casio-mj-12d-calculator",
    "title": "Casio MJ-12D Calculator",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹423",
    "numericPrice": 423,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT0bPzfA2_4JJNa-4rgN6ZSRoTdxRFBLtjExjMQ-yS_Hc8rDgv6YLGqgrYAace3Cv1ftEtDdwvgpNlt-fmo3vrfaLFEzZfT",
    "link": "http://www.flipkart.com/casio-mj-12d-bk-desktop-basic-calculator/p/itmf5nrzqgcqkqgz?pid=CALEGGVZTFHPSACB&lid=LSTCALEGGVZTFHPSACBNAYDCP&marketplace=HYPERLOCAL&cmpid=content_calculator_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-casio-mj-12d-calculator",
    "title": "Casio MJ-12D Calculator",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹440",
    "numericPrice": 440,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT0bPzfA2_4JJNa-4rgN6ZSRoTdxRFBLtjExjMQ-yS_Hc8rDgv6YLGqgrYAace3Cv1ftEtDdwvgpNlt-fmo3vrfaLFEzZfT",
    "link": "https://www.amazon.in/Casio-MJ-12D-Desktop-Calculator-Grey/dp/B0752LL57V?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A1WYWER0W24N8S",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-satyamstationers-com-2-casio-mj-12d-calculator",
    "title": "Casio MJ-12D Calculator",
    "store": "Satyam Stationers",
    "domain": "satyamstationers.com",
    "price": "₹399",
    "numericPrice": 399,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcT0bPzfA2_4JJNa-4rgN6ZSRoTdxRFBLtjExjMQ-yS_Hc8rDgv6YLGqgrYAace3Cv1ftEtDdwvgpNlt-fmo3vrfaLFEzZfT",
    "link": "https://www.satyamstationers.com/products/casio-mj-12d-150-steps-check-and-correct-desktop-calculator-black?variant=44503424139545&country=IN&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOor9ROqoJ-OdSxOEktt0aAHDJskMNgAneyNAurJPvV8C15fm8VXOJNQ",
    "availability": "Current listing on Satyam Stationers",
    "sourceType": "text"
  },
  {
    "id": "preload-milton-in-0-milton-thermosteel-bottle",
    "title": "Milton Thermosteel Bottle",
    "store": "Milton.in",
    "domain": "milton.in",
    "price": "₹702",
    "numericPrice": 702,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSl7scFnk8d1h5VJzjx9NRkn6CTYCNx3MLiTr5f-buDCs465ASZd7WUAkHpCc15gkV89hdyaWnDgUsCqiaKfIF6wzx0r0icFxc5-xKfch3GvE2AuCFmC7bZwUdg",
    "link": "https://www.milton.in/products/duo-deluxe-thermosteel-water-bottle?variant=48689040031844&srsltid=AfmBOopH0Zz9AQGGRYhELGw1H96576O_AbwndCXtp9oPTIBRYoXheKw3mBY",
    "availability": "Current listing on Milton.in",
    "sourceType": "text"
  },
  {
    "id": "preload-satyamstationers-com-1-milton-thermosteel-bottle",
    "title": "Milton Thermosteel Bottle",
    "store": "Satyam Stationers",
    "domain": "satyamstationers.com",
    "price": "₹685",
    "numericPrice": 685,
    "image": "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSl7scFnk8d1h5VJzjx9NRkn6CTYCNx3MLiTr5f-buDCs465ASZd7WUAkHpCc15gkV89hdyaWnDgUsCqiaKfIF6wzx0r0icFxc5-xKfch3GvE2AuCFmC7bZwUdg",
    "link": "https://www.satyamstationers.com/products/milton-duo-dlx-500-thermosteel-24-hours-hot-and-cold-water-bottle-1-piece-500-ml-100-leak-proof-office-bottle-gym-home-kitchen-hiking-trekking-travel-bottle?variant=47631768486169&country=IN&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOorIUUSzHg9xNHVj8nvXBPlrfnTVZDpAKlOUyNFsKbAoaTiHfgskwnI",
    "availability": "Current listing on Satyam Stationers",
    "sourceType": "text"
  },
  {
    "id": "preload-zepto-com-0-borosil-hydra-bottle",
    "title": "Borosil Hydra Bottle",
    "store": "Zepto",
    "domain": "zepto.com",
    "price": "₹537",
    "numericPrice": 537,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT8u1BI2uIPwiiX3AKTGMqtD4HwnhiCODlBsW4kD8WM6_akHQ5MNqCmtbJYzNSlRjCP94oN-sRrSh91epaYLIKAIUPWe5trWwb0Ve2uRYmDXbBlL4dz2C8gzIE",
    "link": "https://www.zepto.com/pn/borosil-stainless-steel-hydra-trek-vacuum-insulated-flask-water-bottle-500-ml-black/pvid/483ff9eb-7348-4aa4-a2e0-5c28418286e9?srsltid=AfmBOopUK0kl1fU62haO0E2_C0SXbJ_VFBqdTlqJFalzDO1WOJ-_xEXnVkE",
    "availability": "Current listing on Zepto",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-borosil-hydra-bottle",
    "title": "Borosil Hydra Bottle",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹708",
    "numericPrice": 708,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT8u1BI2uIPwiiX3AKTGMqtD4HwnhiCODlBsW4kD8WM6_akHQ5MNqCmtbJYzNSlRjCP94oN-sRrSh91epaYLIKAIUPWe5trWwb0Ve2uRYmDXbBlL4dz2C8gzIE",
    "link": "https://www.amazon.in/Borosil-Stainless-Steel-Bottle-Green/dp/B07DY9CC23?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=AXOGFIT0PZZ7G",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-myborosil-com-2-borosil-hydra-bottle",
    "title": "Borosil Hydra Bottle",
    "store": "myborosil.com",
    "domain": "myborosil.com",
    "price": "₹760",
    "numericPrice": 760,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT8u1BI2uIPwiiX3AKTGMqtD4HwnhiCODlBsW4kD8WM6_akHQ5MNqCmtbJYzNSlRjCP94oN-sRrSh91epaYLIKAIUPWe5trWwb0Ve2uRYmDXbBlL4dz2C8gzIE",
    "link": "https://myborosil.com/products/hydra-thermoflask-water-bottle-trek-black-500-ml?variant=45897588998282&country=IN&currency=INR&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOorwB8WB1wW9BPjh2bG3K4l3sWqfMkzOhdYaOyFbWeZo80Of_LGlp9A",
    "availability": "Current listing on myborosil.com",
    "sourceType": "text"
  },
  {
    "id": "preload-jiomart-com-3-borosil-hydra-bottle",
    "title": "Borosil Hydra Bottle",
    "store": "JioMart",
    "domain": "jiomart.com",
    "price": "₹839",
    "numericPrice": 839,
    "image": "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT8u1BI2uIPwiiX3AKTGMqtD4HwnhiCODlBsW4kD8WM6_akHQ5MNqCmtbJYzNSlRjCP94oN-sRrSh91epaYLIKAIUPWe5trWwb0Ve2uRYmDXbBlL4dz2C8gzIE",
    "link": "https://www.jiomart.com/product/borosil-hydra-trek-green-700-ml-stainless-steel-double-wall-vacuum-insulated-flask-water-bottle-20-hours-hot-24-hours-cold-mj7i3l-53290527?source=shoppingads",
    "availability": "Current listing on JioMart",
    "sourceType": "text"
  },
  {
    "id": "preload-myntra-com-0-giva-sterling-silver-ring",
    "title": "GIVA Sterling Silver Ring",
    "store": "Myntra - MNow",
    "domain": "myntra.com",
    "price": "₹2,645",
    "numericPrice": 2645,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTmgdUWb0NkZwrK2MIzblO5dWMJj4dPKXkT9Q-6x94yocU0MCFofwFlnSB8iMPPtei_eD-3XMczZVi-qAFSupRCknCh31RTh1NNabcEuAzxMAQOHzpM8kpub1o",
    "link": "http://www.myntra.com/Ring/GIVA/GIVA-925-Sterling-Silver-Rhodium-Plated-Cubic-Zirconia-Studded-Adjustable-Finger-Ring/26538196/buy",
    "availability": "Current listing on Myntra - MNow",
    "sourceType": "text"
  },
  {
    "id": "preload-tatacliq-com-1-giva-sterling-silver-ring",
    "title": "GIVA Sterling Silver Ring",
    "store": "Tata CLiQ Fashion",
    "domain": "tatacliq.com",
    "price": "₹2,294",
    "numericPrice": 2294,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTmgdUWb0NkZwrK2MIzblO5dWMJj4dPKXkT9Q-6x94yocU0MCFofwFlnSB8iMPPtei_eD-3XMczZVi-qAFSupRCknCh31RTh1NNabcEuAzxMAQOHzpM8kpub1o",
    "link": "https://www.tatacliq.com/giva-925-sterling-silver-ring-for-women/p-mp000000028829418?tc=true",
    "availability": "Current listing on Tata CLiQ Fashion",
    "sourceType": "text"
  },
  {
    "id": "preload-flipkart-com-2-giva-sterling-silver-ring",
    "title": "GIVA Sterling Silver Ring",
    "store": "Flipkart",
    "domain": "flipkart.com",
    "price": "₹2,699",
    "numericPrice": 2699,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTmgdUWb0NkZwrK2MIzblO5dWMJj4dPKXkT9Q-6x94yocU0MCFofwFlnSB8iMPPtei_eD-3XMczZVi-qAFSupRCknCh31RTh1NNabcEuAzxMAQOHzpM8kpub1o",
    "link": "https://www.flipkart.com/giva-sterling-silver-zircon-rhodium-plated-ring/p/itm84c97d0701484?pid=RNGHGMHRV9CM9DDB&lid=LSTRNGHGMHRV9CM9DDBLYXR0N&marketplace=FLIPKART&cmpid=content_ring_8965229628_gmc",
    "availability": "Current listing on Flipkart",
    "sourceType": "text"
  },
  {
    "id": "preload-lifestylestores-com-3-giva-sterling-silver-ring",
    "title": "GIVA Sterling Silver Ring",
    "store": "Lifestylestores.com",
    "domain": "lifestylestores.com",
    "price": "₹2,789",
    "numericPrice": 2789,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTmgdUWb0NkZwrK2MIzblO5dWMJj4dPKXkT9Q-6x94yocU0MCFofwFlnSB8iMPPtei_eD-3XMczZVi-qAFSupRCknCh31RTh1NNabcEuAzxMAQOHzpM8kpub1o",
    "link": "https://www.lifestylestores.com/in/en/SHOP-Giva-Silver-GIVA-Sterling-Silver-Infinity-Heart-Ring-For-Women/p/1000014798307?srsltid=AfmBOoqs2k0FqZX1dQTdBVLdUUAjDld3OC_2Gjg2DapwiXxCHLR_6YTl5gs",
    "availability": "Current listing on Lifestylestores.com",
    "sourceType": "text"
  },
  {
    "id": "preload-voylla-com-0-voylla-oxidised-jhumka-earrings",
    "title": "Voylla Oxidised Jhumka Earrings",
    "store": "voylla.com",
    "domain": "voylla.com",
    "price": "₹569",
    "numericPrice": 569,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRbG2Y_H_rlnwLM2iu0bO2vC-kNGHi9mmaAx4_xyIOBnehvhEP8UOfbawrBkrDwYR0U4HiKWQ42wmOTjIkTD381qANAOLSBU53LJjQKtRR5",
    "link": "https://www.voylla.com/products/rava-ball-oxidized-jhumka-style-earrings-vmjai43246?variant=43178784915622&srsltid=AfmBOorXGB7K59hdnZJROC9qwwokJo-Y-ImX73iy_Ys1XlhxcCWO061Aje0",
    "availability": "Current listing on voylla.com",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-1-voylla-oxidised-jhumka-earrings",
    "title": "Voylla Oxidised Jhumka Earrings",
    "store": "amazon.in",
    "domain": "amazon.in",
    "price": "₹460",
    "numericPrice": 460,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRbG2Y_H_rlnwLM2iu0bO2vC-kNGHi9mmaAx4_xyIOBnehvhEP8UOfbawrBkrDwYR0U4HiKWQ42wmOTjIkTD381qANAOLSBU53LJjQKtRR5",
    "link": "https://www.amazon.in/Voylla-Oxidized-Jhumka-Style-Earrings/dp/B091Z4HGLF",
    "availability": "Current listing on amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-eternz-com-2-voylla-oxidised-jhumka-earrings",
    "title": "Voylla Oxidised Jhumka Earrings",
    "store": "Eternz",
    "domain": "eternz.com",
    "price": "₹679",
    "numericPrice": 679,
    "image": "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRbG2Y_H_rlnwLM2iu0bO2vC-kNGHi9mmaAx4_xyIOBnehvhEP8UOfbawrBkrDwYR0U4HiKWQ42wmOTjIkTD381qANAOLSBU53LJjQKtRR5",
    "link": "https://www.eternz.com/products/rava-ball-oxidized-jhumka-style-earrings?srsltid=AfmBOoqc2nfzK20eXB3BvS8DIVxBKty7_vx8j37irJulkXtEhAnQu3K4W7A",
    "availability": "Current listing on Eternz",
    "sourceType": "text"
  },
  {
    "id": "preload-amazon-in-0-miniso-sticker-pack",
    "title": "Miniso Sticker Pack",
    "store": "Amazon.in",
    "domain": "amazon.in",
    "price": "₹190",
    "numericPrice": 190,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR00Ym20Zj2TxnqYYZjA4sOfSdylk05IpXopJGROqlY6iCN2D_4N3UW3Dl1s-fc681583n31RS0XQwqGW9urC2A9fju67y9uTumBVr7pQMVzwXtoOSqeIZpcw",
    "link": "https://www.amazon.in/FunBlast-Stickers-20-Stickers-Japanese-Sheet-40/dp/B0C49X79P2?source=ps-sl-shoppingads-lpcontext&ref_=fplfs&psc=1&smid=A3LH2KKDFG65UB",
    "availability": "Current listing on Amazon.in",
    "sourceType": "text"
  },
  {
    "id": "preload-meesho-com-1-miniso-sticker-pack",
    "title": "Miniso Sticker Pack",
    "store": "Meesho",
    "domain": "meesho.com",
    "price": "₹132",
    "numericPrice": 132,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR00Ym20Zj2TxnqYYZjA4sOfSdylk05IpXopJGROqlY6iCN2D_4N3UW3Dl1s-fc681583n31RS0XQwqGW9urC2A9fju67y9uTumBVr7pQMVzwXtoOSqeIZpcw",
    "link": "https://www.meesho.com/funblast-cute-cartoon-theme-kawaii-stickers-20-pet-sheets-cute-washi-stickers-for-projectjapanese-style-girls-paper-sticker-setsize-of-each-sheet-40x8cmscolordesign-may-varyself-adhesive/p/9n95la?utm_source=google&utm_medium=cpc&utm_term=gmc&srsltid=AfmBOopH_P0nzZyWQZqc2ckyxB05_tNBuuiWfUB-PtcOH2dF_H6aVzz8sBA",
    "availability": "Current listing on Meesho",
    "sourceType": "text"
  },
  {
    "id": "preload-funblast-in-2-miniso-sticker-pack",
    "title": "Miniso Sticker Pack",
    "store": "FunBlast",
    "domain": "funblast.in",
    "price": "₹259",
    "numericPrice": 259,
    "image": "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR00Ym20Zj2TxnqYYZjA4sOfSdylk05IpXopJGROqlY6iCN2D_4N3UW3Dl1s-fc681583n31RS0XQwqGW9urC2A9fju67y9uTumBVr7pQMVzwXtoOSqeIZpcw",
    "link": "https://funblast.in/products/cute-cartoon-theme-kawaii-stickers-20-pet-sheets-cute-washi-stickers-for-project-japanese-style-girls-sticker-set-size-of-each-sheet-40-x-8-cm-color-and-design-may-vary",
    "availability": "Current listing on FunBlast",
    "sourceType": "text"
  }
];
