import type { ProductListing } from "@/lib/search";

export const demoBrowseListings: ProductListing[] = [
  {
    id: "demo-amazon-linen-trouser",
    title: "Ivory Linen Wide Leg Trouser",
    store: "Amazon.in",
    domain: "amazon.in",
    price: "₹1,299",
    numericPrice: 1299,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    link: "https://www.amazon.in/",
    availability: "Soft linen blend, relaxed fit",
    sourceType: "text",
  },
  {
    id: "demo-myntra-linen-trouser",
    title: "Ivory Linen Wide Leg Trouser",
    store: "Myntra",
    domain: "myntra.com",
    price: "₹1,449",
    numericPrice: 1449,
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=80",
    link: "https://www.myntra.com/",
    availability: "Sizes XS to XL",
    sourceType: "text",
  },
  {
    id: "demo-ajio-crossbody",
    title: "Black Mini Crossbody Bag",
    store: "AJIO",
    domain: "ajio.com",
    price: "₹899",
    numericPrice: 899,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=80",
    link: "https://www.ajio.com/",
    availability: "Compact daily carry",
    sourceType: "text",
  },
  {
    id: "demo-flipkart-crossbody",
    title: "Black Mini Crossbody Bag",
    store: "Flipkart",
    domain: "flipkart.com",
    price: "₹1,049",
    numericPrice: 1049,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=800&q=80",
    link: "https://www.flipkart.com/",
    availability: "Faux leather finish",
    sourceType: "text",
  },
  {
    id: "demo-nykaa-lip-tint",
    title: "Berry Glaze Lip Tint",
    store: "Nykaa",
    domain: "nykaa.com",
    price: "₹549",
    numericPrice: 549,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80",
    link: "https://www.nykaa.com/",
    availability: "Glossy tint, 6 ml",
    sourceType: "text",
  },
  {
    id: "demo-meesho-lip-tint",
    title: "Berry Glaze Lip Tint",
    store: "Meesho",
    domain: "meesho.com",
    price: "₹399",
    numericPrice: 399,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80",
    link: "https://www.meesho.com/",
    availability: "Budget pick",
    sourceType: "text",
  },
  {
    id: "demo-tatacliq-watch",
    title: "Gold Mesh Strap Watch",
    store: "Tata CLiQ",
    domain: "tatacliq.com",
    price: "₹2,199",
    numericPrice: 2199,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    link: "https://www.tatacliq.com/",
    availability: "Minimal dial",
    sourceType: "text",
  },
  {
    id: "demo-amazon-watch",
    title: "Gold Mesh Strap Watch",
    store: "Amazon.in",
    domain: "amazon.in",
    price: "₹1,999",
    numericPrice: 1999,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
    link: "https://www.amazon.in/",
    availability: "Prime eligible",
    sourceType: "text",
  },
  {
    id: "demo-jiomart-headphones",
    title: "Cream Wireless Headphones",
    store: "JioMart",
    domain: "jiomart.com",
    price: "₹1,799",
    numericPrice: 1799,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    link: "https://www.jiomart.com/",
    availability: "40 hour battery",
    sourceType: "text",
  },
  {
    id: "demo-flipkart-headphones",
    title: "Cream Wireless Headphones",
    store: "Flipkart",
    domain: "flipkart.com",
    price: "₹1,649",
    numericPrice: 1649,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
    link: "https://www.flipkart.com/",
    availability: "Noise isolation",
    sourceType: "text",
  },
  {
    id: "demo-myntra-sneakers",
    title: "White Everyday Sneakers",
    store: "Myntra",
    domain: "myntra.com",
    price: "₹1,899",
    numericPrice: 1899,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80",
    link: "https://www.myntra.com/",
    availability: "Sizes 4 to 9",
    sourceType: "text",
  },
  {
    id: "demo-snapdeal-sneakers",
    title: "White Everyday Sneakers",
    store: "Snapdeal",
    domain: "snapdeal.com",
    price: "₹1,599",
    numericPrice: 1599,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=80",
    link: "https://www.snapdeal.com/",
    availability: "Low-top lace up",
    sourceType: "text",
  },
];
